version: '3.4'
services:
  metadataapi:
    build:
      context: .
      dockerfile: MetadataService-src/MetadataService.API/Dockerfile
    image: metadataapi:1.0.0
    environment:
      - ConnectionStrings:InsuranceConnection= fhgfh
      - Cache:AWSRedisEndPoint= hgjjh
    ports:
      - "8080:80"
  policyapi:
    build:
      context: .
      dockerfile: PolicyService-src/PolicyService.API/Dockerfile
    image: policyapi:1.0.0
    environment:
      - Cache:AWSRedisEndPoint= test
    ports:
      - "8081:80"
  